name: Check Secrets

on:
  # 触发条件：手动触发或推送代码时运行
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      # 检查 GitHub Actions 的上下文
      - name: Dump GitHub Context
        run: echo "${{ toJson(github) }}"

      # 检查是否能正确读取 secrets
      - name: Check Secrets
        run: |
          echo "WRT_WIFI_PW: ${{ secrets.WRT_WIFI_PW }}"
          if [ -z "${{ secrets.WRT_WIFI_PW }}" ]; then
            echo "Error: WRT_WIFI_PW is empty or not set!"
            exit 1
          else
            echo "WRT_WIFI_PW is correctly set."
          fi

      # 将 secrets 作为环境变量传递
      - name: Use Secrets as Environment Variable
        env:
          WIFI_PASSWORD: ${{ secrets.WRT_WIFI_PW }}
        run: |
          echo "WiFi Password from environment variable: $WIFI_PASSWORD"
          if [ -z "$WIFI_PASSWORD" ]; then
            echo "Error: WIFI_PASSWORD is empty or not set!"
            exit 1
          else
            echo "WIFI_PASSWORD is correctly set."
          fi
